In [6]:
import pandas as pd

# GAZE

In [8]:
pd.read_csv("results/expR1_accuracy_gaze.csv")

    Method Dataset      RMSE        R2   Time_sec
0     PINN    gaze  0.234287  0.936458   6.742899
1      MLP    gaze  0.205427  0.951148   1.708574
2  DeepMLP    gaze  0.187908  0.959126   5.484272
3   ResMLP    gaze  0.211575  0.948181   5.875221
4    CNN1D    gaze  0.254934  0.924765   2.344028
5     LSTM    gaze  0.520377  0.686527  47.320148
6     QKRR    gaze  0.196228  0.955426   1.494734

# HOUSEHOLD

In [9]:
pd.read_csv("results/expR1_accuracy_household.csv")

    Method    Dataset      RMSE        R2  Time_sec
0     PINN  household  0.371023  0.868808  3.185203
1      MLP  household  0.292122  0.918673  0.357004
2  DeepMLP  household  0.259402  0.935871  0.655442
3   ResMLP  household  0.227037  0.950875  0.746773
4    CNN1D  household  0.425442  0.827501  0.266477
5     LSTM  household  0.729476  0.492859  8.303194
6     QKRR  household  0.239712  0.945237  0.306387

# ISE

In [10]:
pd.read_csv("results/expR1_accuracy_ise.csv")

    Method Dataset      RMSE        R2  Time_sec
0     PINN     ise  0.302159  0.847079  2.466972
1      MLP     ise  0.303991  0.845219  0.283309
2  DeepMLP     ise  0.299080  0.850180  0.412568
3   ResMLP     ise  0.315250  0.833542  0.433912
4    CNN1D     ise  0.315406  0.833378  0.249180
5     LSTM     ise  0.449355  0.661800  3.419919
6     QKRR     ise  0.294038  0.855189  0.179900

# NO2

In [11]:
pd.read_csv("results/expR1_accuracy_no2.csv")

    Method Dataset      RMSE        R2   Time_sec
0     PINN     no2  0.638220  0.596791  21.970315
1      MLP     no2  0.641910  0.592114   7.635127
2  DeepMLP     no2  0.686491  0.533492  13.591341
3   ResMLP     no2  0.679993  0.542281   4.827520
4    CNN1D     no2  0.635725  0.599937   2.374154
5     LSTM     no2  0.735483  0.464530  21.646084
6     QKRR     no2  0.622629  0.616251   1.556589

# NSL-KDD

In [12]:
pd.read_csv("results/expR1_accuracy_nslkdd.csv")

    Method Dataset      RMSE        R2  Time_sec
0     PINN  nslkdd  0.498661  0.762701  2.790973
1      MLP  nslkdd  0.486746  0.773906  0.308153
2  DeepMLP  nslkdd  0.449773  0.806949  0.645339
3   ResMLP  nslkdd  0.448729  0.807844  0.794709
4    CNN1D  nslkdd  0.526063  0.735905  0.328278
5     LSTM  nslkdd  0.602692  0.653362  7.921137
6     QKRR  nslkdd  0.442077  0.813499  0.224573